language: php
sudo: false

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

env:
  - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --no-suggest"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install
  
before_script:
  - cp ./tests/_config/TestConfiguration.travis.php ./tests/_config/TestConfiguration.php

script:
  - composer test

